// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCNm556PfhEZ_BcYhFmdpKFcw_TFTfehE',
    appId: '1:779418651842:web:cd2d6b6bc8567e7eab7f5b',
    messagingSenderId: '779418651842',
    projectId: 'next-gen-tools',
    authDomain: 'next-gen-tools.firebaseapp.com',
    storageBucket: 'next-gen-tools.firebasestorage.app',
    measurementId: 'G-LGZ8WKHW9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhdkcCTsY0bgZ0uNu5MFSVEF-rLP4MGr8',
    appId: '1:779418651842:android:a95613d9bb3830c9ab7f5b',
    messagingSenderId: '779418651842',
    projectId: 'next-gen-tools',
    storageBucket: 'next-gen-tools.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq34uVlf3yq9KF5mBtx1y82zQReqboR8w',
    appId: '1:779418651842:ios:96a5efdd625d38c3ab7f5b',
    messagingSenderId: '779418651842',
    projectId: 'next-gen-tools',
    storageBucket: 'next-gen-tools.firebasestorage.app',
    iosBundleId: 'com.example.mastertool',
  );
}
